### ISSUE TITLE
error in manage.py

### ISSUE THREAD

**Issue by naturzukunft** [tOkeshu/activitypub-example#1]
if i start the commands as described, the following error occurs:
```
Traceback (most recent call last):
  File "./activitypub-example/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/activitypub-example/activitypub/models.py", line 60, in <module>
    class Note(Model):
  File "/activitypub-example/activitypub/models.py", line 64, in Note
    person  = ForeignKey(Person, related_name='notes')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

```

**Comment by chanyou0311** [comment]
@naturzukunft 

In Django version 2.0 or later, ForeignKey requires on_delete argument.

> The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.

https://docs.djangoproject.com/en/2.2/releases/2.0/#features-removed-in-2-0

To avoid errors, I think it is easy to install Django by specifying a version.

```
pip install django==1.11.22
```

**Comment by barslmn** [comment]
Or you can add argument of `on_delete=models.CASCADE` to foreign key fields.
More here: https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.ForeignKey.on_delete
